[project]
name = "whisper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "mlx-whisper>=0.4.2",
    "numpy>=2.2.4",
    "sounddevice>=0.5.1",
    "soundfile>=0.13.1",
]
